

```{r}
combined_df <- readRDS(file=fs::path(r_objects_folder, "060_combined_df.rds"))
test_info_pred <- readRDS(file=fs::path(r_objects_folder, "060_test_info_pred.rds"))
test_info <- readRDS(file=fs::path(r_objects_folder, "051_test_info.rds"))


```

```{r}
test_info <- test_info %>%
  bind_cols(test_info_pred) %>%
  select(-lower, -upper)
```

```{r}
#| fig-cap: Test Information curve of predicted 3D-CAM in Intuit and SAGES
#| fig-cap-location: top
#| label: fig-test_info_pred_3dcam



test_info %>%
  filter(yhat>=0) %>%
ggplot(aes(x = yhat, y = i, color = study)) +
  geom_line() +
  scale_x_continuous("Predicted 3D-CAM") +
  scale_y_continuous("Information") +
  geom_rug(data=combined_df, mapping=aes(x = harmonized_3dcam, color = study), inherit.aes = FALSE, alpha = .2) +
  scale_color_manual("Study", values = c(SAGES = "#d95f02", Intuit = "#7570b3"),
                       labels = c(SAGES = "SAGES", INTUIT_ACTIVE = "Intuit")) +
  hrbrthemes::theme_ipsum()

ggsave(here::here("Figures", "Duke_harmonization_test_info_pred_3dcam.pdf"), device = cairo_pdf)



```


```{r}
#| fig-cap: Test SEM curve of predicted 3D-CAM in Intuit and SAGES
#| fig-cap-location: top
#| label: fig-test_sem_pred_3dcam

test_info %>%
  filter(yhat>=0) %>%
ggplot(aes(x = yhat, y = sem, color = study)) +
  geom_hline(yintercept = 0.31) +
  geom_line() +
  scale_x_continuous("Predicted 3D-CAM", breaks = seq(0, 12, 2)) +
  scale_y_continuous("SEM", limits = c(0, 2)) +
  geom_rug(data=combined_df, mapping=aes(x = harmonized_3dcam, color = study), inherit.aes = FALSE, alpha = .2) +
  scale_color_manual("Study", values = c(SAGES = "#d95f02", Intuit = "#7570b3"),
                       labels = c(SAGES = "SAGES", INTUIT_ACTIVE = "Intuit")) +
  hrbrthemes::theme_ipsum()

ggsave(here::here("Figures", "Duke_harmonization_test_sem_pred_3dcam.pdf"), device = cairo_pdf)

test_info %>%
  filter(yhat>=0) %>%
ggplot(aes(x = yhat, y = sem, color = study)) +
  geom_hline(yintercept = 0.31) +
  geom_point(data=combined_df, mapping=aes(x = yhat, y = F_SE, color = study), alpha = .2) +
  geom_line() +
  scale_x_continuous("Predicted 3D-CAM", breaks = seq(0, 12, 2), limits = c(0, 12)) +
  scale_y_continuous("SEM", limits = c(0, 2)) +
  scale_color_manual("Study", values = c(SAGES = "#d95f02", Intuit = "#7570b3"),
                       labels = c(SAGES = "SAGES", INTUIT_ACTIVE = "Intuit")) +
  hrbrthemes::theme_ipsum()
ggsave(here::here("Figures", "Duke_harmonization_test_sem_pred_3dcam-2.pdf"), device = cairo_pdf)

combined_df %>%
ggplot(aes(x = yhat, y = F_SE, color = study)) +
  geom_hline(yintercept = 0.31) +
  geom_point(alpha = .2) +
  geom_smooth(se=FALSE) +
  scale_x_continuous("Predicted 3D-CAM", breaks = seq(0, 12, 2), limits = c(0, 12)) +
  scale_y_continuous("SEM", limits = c(0, 2)) +
  scale_color_manual("Study", values = c(SAGES = "#d95f02", Intuit = "#7570b3"),
                       labels = c(SAGES = "SAGES", INTUIT_ACTIVE = "Intuit")) +
  hrbrthemes::theme_ipsum()
ggsave(here::here("Figures", "Duke_harmonization_test_sem_pred_3dcam-3.pdf"), device = cairo_pdf)

```

